name: TODO
on:
  push:
    branches:
      - master

jobs:
  issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: todo-actions
        uses: floffah/todo-actions@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}
